server.port=8081
spring.application.name=identity-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/edulink_identity?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=root
=======
spring.datasource.password=Mysql@244
>>>>>>> 7cd35352abea80eb91e75cf8ea2946e5a5613c06
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=edulinkSecretKey2024VeryLongSecretKeyForJWTGenerationEduLinkSystem
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Logging
logging.level.com.edulink=DEBUG
